language: node_js

branches:
  only:
    - master

node_js:
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"

before_install:
  - npm install --global yarn@^1.22
  - yarn set version berry

install:
  - yarn run setup

after_script:
  - yarn run codecov
