plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.js

# Nest.js doesn't play nice with PnP yet :(
nodeLinker: node-modules
